apiVersion: batch/v1
kind: CronJob
metadata:
  name: cron-1
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: teste
            image: busybox
            args:
            - /bin/sh
            - -c
            - date; echo "teste executado - dormir 20 segundos";sleep 30
          restartPolicy: OnFailure