apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: meu-prometheus
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2021-09-24T13:10:47Z"
  labels:
    app: prometheus
    app.kubernetes.io/managed-by: Helm
    chart: prometheus-14.7.1
    component: server
    heritage: Helm
    release: meu-prometheus
  name: meu-prometheus-server
  namespace: default
  resourceVersion: "403034"
  uid: 997a0791-3175-446f-9319-05fb62c9f043
spec:
  clusterIP: 10.104.74.195
  clusterIPs:
  - 10.104.74.195
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 9090
  selector:
    app: prometheus
    component: server
    release: meu-prometheus
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
