name: Auto-update
on:
  workflow_run:
    branches: master
    workflows:
      - "Continuous Integration"
    types:
      - completed

jobs:
  autoupdate:
    name: Auto-update PRs
    runs-on: ubuntu-20.04
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: peter-evans/rebase@v1
        with:
          token: ${{ secrets.NGINX_PAT }}
          exclude-labels: |
            no-autoupdate
            dependencies
