apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: teste-path
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: thiagoirch.com
    http:
      paths:
      - path: "/app"
        pathType: Prefix
        backend:
          service:
            name: httpd
            port:
              number: 32222
  ingressClassName: nginx
